spring.application.name=smartchef

spring.jpa.properties.hibernate.dialect = org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.default_schema=public

spring.datasource.url=jdbc:postgresql://dpg-d5thiqfpm1nc739cc35g-a.frankfurt-postgres.render.com:5432/smartchef_db_dwp2
#spring.datasource.url=jdbc:postgresql://localhost:5433/smartchef_db
spring.datasource.username=smartchef_user
#spring.datasource.username=postgres
spring.datasource.password=sZF75MVppmzZSxiO84UCZd8483gT58wd
#spring.datasource.password=dam2

spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB
server.tomcat.max-swallow-size=-1
server.tomcat.max-http-form-post-size=10MB