spring.application.name=smartchef

spring.jpa.properties.hibernate.dialect = org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.default_schema=public

spring.datasource.url=jdbc:postgresql://dpg-d5thiqfpm1nc739cc35g-a.frankfurt-postgres.render.com/smartchef_db_dwp2
spring.datasource.username=postgres
spring.datasource.password=dam2
